apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadsmrf3144-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadsmrf3144-tenant-component
    app.kubernetes.io/part-of: loadsmrf3144-tenant-app
  name: loadsmrf3144-tenant-component
  namespace: loadsmrf3144-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadsmrf3144-tenant-component
    weight: null
status: {}
